name: widcy
description: WIDCYApp

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  # flutter_facebook_auth: <latest_version>

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  easy_localization: ^3.0.3

  firebase_core: 2.24.2
  firebase_auth: 4.15.2
  cloud_firestore: 4.13.5
  firebase_messaging: 14.7.8
  libphonenumber: ^2.0.2
  smooth_page_indicator: ^1.1.0
  firebase_database: ^10.3.8
  image_card: ^0.0.4
  firebase_storage: ^11.5.6
  provider: ^6.1.1
  intl: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.7
  json_serializable: ^6.7.1
  flutter_lints: 3.0.1

flutter:

  uses-material-design: true
  generate: true

  assets:
    - images/
    - assets/font/
    - assets/profile/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Hanuman
     fonts:
       - asset: assets/font/Hanuman-Bold.ttf
       - asset: assets/font/Hanuman-Light.ttf
       - asset: assets/font/Hanuman-Regular.ttf
   - family: NotoSansKhmer
     fonts:
       - asset: assets/font/NotoSansKhmer.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
