// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjJbXVlAHoXT5BUIa6LKU4jPwPIs3uW7E',
    appId: '1:726133835278:web:04c71f464c1328f8c01e5f',
    messagingSenderId: '726133835278',
    projectId: 'widcy-ebba3',
    authDomain: 'widcy-ebba3.firebaseapp.com',
    databaseURL: 'https://widcy-ebba3-default-rtdb.firebaseio.com',
    storageBucket: 'widcy-ebba3.appspot.com',
    measurementId: 'G-1SMW2XQMCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjJbXVlAHoXT5BUIa6LKU4jPwPIs3uW7E',
    appId: '1:726133835278:android:e1f6531cd4c4c359c01e5f',
    messagingSenderId: '726133835278',
    projectId: 'widcy-ebba3',
    databaseURL: 'https://widcy-ebba3-default-rtdb.firebaseio.com',
    storageBucket: 'widcy-ebba3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxzzrxgGAOHCLD3edGqzQeXZQe_9lsHHA',
    appId: '1:726133835278:ios:8f96f6c3d749166cc01e5f',
    messagingSenderId: '726133835278',
    projectId: 'widcy-ebba3',
    databaseURL: 'https://widcy-ebba3-default-rtdb.firebaseio.com',
    storageBucket: 'widcy-ebba3.appspot.com',
    iosBundleId: 'com.example.widcy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxzzrxgGAOHCLD3edGqzQeXZQe_9lsHHA',
    appId: '1:726133835278:ios:8f96f6c3d749166cc01e5f',
    messagingSenderId: '726133835278',
    projectId: 'widcy-ebba3',
    databaseURL: 'https://widcy-ebba3-default-rtdb.firebaseio.com',
    storageBucket: 'widcy-ebba3.appspot.com',
    iosBundleId: 'com.example.widcy',
  );
}
